# Inspiration: https://github.com/edx/configuration/blob/master/.travis.yml
env: 
  global: 
    #- IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - MOSEKLM_LICENSE_FILE=/home/travis/build/testbot/restricted/mosek.lic
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/testbot/restricted/cplex/cplex/include:/home/travis/build/testbot/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/testbot/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/testbot/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/testbot/restricted/cplex/access.ilm
    - WORHP=/home/travis/build/testbot/restricted/worhp
    - WORHP_LICENSE_FILE=/home/travis/build/testbot/restricted/worhp/unlocked.lic
    - SNOPT=/home/travis/build/snopt75
    - MATLABPATH=/home/travis/build/matlab-install
    - MATLAB_ROOT=/home/travis/build/matlab
    - MATLABRELEASE=R2014a
    - SLURP_OS=trusty
  matrix:
    - FOO=A
    - FOO=B
    - FOO=C
    - FOO=D
    - FOO=E
    - FOO=F
    - FOO=G
    - FOO=H  

before_script:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses

compiler: gcc
dist: trusty
language: generic
script:
  - sudo apt-get install -y gcc-4.7 g++-4.7 gfortran-4.7
  - export CC=gcc-4.7
  - export CXX=g++-4.7

  # travis-wait seems to stop at 20 mins, regardless if output is being generated
  - (while true ; do sleep 60 ; echo "ping" ; done ) &

  - swig -version
  - pushd /home/travis/build/
  - testbot/recipes/fetch.sh matlab$MATLABRELEASE.tar.gz
  - mkdir matlab && tar -xf matlab$MATLABRELEASE.tar.gz -C matlab
  - popd
  - mkdir build
  - pushd build
  - cmake  -DOLD_LLVM=ON -DCMAKE_INSTALL_PREFIX=/home/travis/build/matlab-install -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_DEEPBIND=ON -DWITH_MATLAB=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_JSON=ON ..
  - make -j2 VERBOSE=1
  - sudo make -j2 install
  - popd
  - matlabtunnel
  - rm docs/examples/matlab/lotka_volterra_minlp.m test/matlab/asorted_tests.m docs/examples/matlab/direct_multiple_shooting.m docs/examples/matlab/direct_single_shooting.m docs/examples/matlab/sysid.m
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
  - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
        
branches:
  except:
    - /.*appveyor.*/

before_install:
  - pushd ../../ && git clone https://github.com/casadi/testbot.git
  - pushd testbot && git checkout merged && source recipes/setup.sh && popd
  - sudo apt-get install p7zip-full -y
  - export SLURP_GCC=4.7
  - slurp swig_matlab
  - slurp hsl
  - slurp clang
  - travis_retry testbot/recipes/fetch.sh mosek7.tar.bz2 && tar -xf mosek7.tar.bz2 && rm mosek7.tar.bz2
  - slurp ecos
  - travis_retry testbot/recipes/fetch.sh snopt75.tar.gz && mkdir snopt75 && tar -xf snopt75.tar.gz -C snopt75 && rm snopt75.tar.gz

  - pushd testbot/restricted/cplex && mkdir cplex && tar -xf cplex12.4.tar.gz -C cplex && mkdir concert && tar -xf cplex12.4-concert.tar.gz -C concert && rm cplex12.4-concert.tar.gz && popd
  - pushd testbot/restricted && mkdir -p worhp && cd  worhp && 7za e ../libworhp_debian7_amd64_gcc47_1.7-12970f3.7z -y && popd
  #- slurp bonmin
  - slurp ipopt
  - popd
  - sudo apt-get update -qq
  - sudo apt-get install -q -y binutils gcc g++ gfortran git cmake liblapack-dev liblapack3 libblas3 ipython python-dev python-numpy python-scipy python-matplotlib libxml2-dev
  - sudo pip install github3.py
 
after_failure:
  - pushd /home/travis/build/testbot/ && python -c "from github3 import login;from testbotcredentials import TestBotCredentials;tbc = TestBotCredentials();login(*tbc.github).repository('casadi','casadi').create_comment(sha='$TRAVIS_COMMIT',body='Failure reported by [travis](https://travis-ci.org/casadi/casadi/jobs/$TRAVIS_JOB_ID) in $TRAVIS_COMMIT_RANGE -- $TRAVIS_TEST_RESULT')" && popd

